# --- fx.conf 最终完整版 ---
[General]
DISABLE_UDP_QUIC = 1

DOWNLOAD_FILE = url=https://v4.gh-proxy.org/https://raw.githubusercontent.com/luke029/sr-rules/main/mhm.yaml, path=/etc/openclash/config/mhm.yaml, cron=0 6 * * *, force=false

CONFIG_FILE = /etc/openclash/config/mhm.yaml

[Overwrite]
# 使用环境变量注入订阅
ruby_map_edit "$CONFIG_FILE" "['proxy-providers']" "订阅" "['url']" "$EN_KEY1"